[general]
language = "java" # typescript

[ai]
model = "qwen2.5-coder:7b"

[git]
review-branch = "feature/kevin/0724/8917"
dest-branch = "release/RC_20250724"

[paths]
repo-location = "/Users/kevintung/code/aibank-ms"
output-dir = "outputs/"
