[project]
name = "code-review-bot"
version = "0.1.0"
description = "Code Review Bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-core>=0.3.68",
    "langchain-ollama>=0.3.3",
]
